---
title: "L2code"
output: html_document
number-sections: true
---

# 数据类型

## 数值型numeric

```{r}
# numeric 数值型，str()查看对象的类型
a1 <- c(1,2,3,4,5)
str(a1)
str(pi)
str(sqrt(2))
```

## 整数型integer

```{r}
# integer 整数型
a2 <- 5L #L 表示该值是整数
str(a2)

# 1:5生成序列1，2，3，4，5
a3 <- 1:5
str(a3)

a4 <- as.numeric(a3)
str(a4)
```


## 逻辑型logical

```{r}
answer <- c(TRUE,TRUE,TRUE,FALSE,TRUE,FALSE) 
#查看answer的类型
str(answer) 

#逻辑型向量求和，TRUE = 1, FALSE = 0
sum(answer) 

#逻辑型向量求平均，TRUE的比例
mean(answer) 

#！逻辑值取反
!answer

```

##  字符串character

```{r}
# data.frame()创建数据框
df <- data.frame(
  id = 1:50,
  age = round(rnorm(50,40,5)),
  edu = c(rep("highschool",20),
          rep("bachelor", 15),
          rep("master",15)),
  sex = ifelse(rbinom(50, 1, 0.6) == 1, 
               "male", "female")
)

head(df) #显示df的前六行
df$edu #edu是字符串，有双引号
```

## 因子factor

```{r}
#factor()将字符串转换为因子，默认level按字母顺序
df$edu <- factor(df$edu) 
#查看因子df$edu的level顺序
levels(df$edu) 
#edu是因子，没有双引号
df$edu 
#箱线图的排列按edu的三个组别的字母顺序
boxplot(df$age ~ df$edu) 

# ordinal scale, levels = 自定义逻辑顺序
df$edu <- factor(df$edu, 
                 levels = c("highschool", "bachelor", "master"))
levels(df$edu)
boxplot(df$age ~ df$edu)
```

```{r}
#将数值型数据转换为因子
df$age_group <- cut(df$age, 4)

#查看因子的水平个数
nlevels(df$age_group)

#呈现age_group和edu的列联表
table(df$age_group, df$edu)
```

# 数据结构

## 向量vector

```{r}
# 向量
# scalar
age <- 5

name <- "Harry"

# numeric vector
a <- c(1,2,3,4,5) # c() Combine Values into a Vector

a[1:3] #提取向量中的元素[ ]

a[a > 3] #提取大于3的元素

a > 3 # 返回逻辑值

# character vector
b <- LETTERS[1:10] 
b[5]
b[c(2,4,6)]
b[1:3]

#logical vector
answer <- c(TRUE,TRUE,TRUE,FALSE,TRUE,FALSE) 

```

## 矩阵matrix

```{r}
# matrix()创建矩阵, 默认按列的方向填充
y1<-matrix(1:20, nrow=5, ncol=4)
y1[3, ] #第3行
y1[, 1] #第2列
y1[1:3, 2:4] #第1-3行的第2-4列

# byrow = TRUE 按行方向填充
y2<-matrix(1:20, nrow=5, ncol=4, byrow = TRUE)
y2[3,2] #第3行第2列


# 矩阵中可以存放字符串
cells <- letters[1:10]
# 定义矩阵的行名、列名
rnames <- c("team1", "team2")
cnames <- c("class1", "class2", "class3", "class4", "class5")
mymatrix <- matrix(cells, nrow=2, ncol=5, byrow=TRUE,
                   dimnames=list(rnames, cnames))
mymatrix["team1", ]
mymatrix[, "class1"]
```

## 数据框dataframe

```{r}
#创建数据框data.frame()
d <- c(1,2,3,4)
e <- c("red", "white", "green", NA)
f <- c(TRUE,TRUE,TRUE,FALSE)
df <- data.frame(id = d,
                 color = e,
                 pass = f)
df
df[1:2] #第1-2列
df[c("id","pass")] #df中的向量id和pass
df$color

View(mtcars) #以表单形式浏览数据框

head(mtcars) #浏览数据框的前六行

tail(mtcars) #浏览数据框的后六行

dim(mtcars) #查看数据框的行数和列数

str(mtcars) #查看数据框的结构
```

## 列表list

```{r}
# 创建列表list
mylist <- list(myvector = y1, 
               mymatrix = cells, 
               mydata = df)

mylist[[1]][2,3] #第1个对象中的第2行第3列
mylist[[3]][, 2] #第3个对象中的第2列

#hist()函数的运行结果被保存为list
x <- runif(100)
p <- hist(x)
p
```


